apiVersion: v2
name: azure-cost-exporter
description: Prometheus exporter for Azure Cost Management API - Monitor and track Azure spending
type: application
version: 1.2.0
appVersion: "1.2.0"
keywords:
  - azure
  - cost
  - prometheus
  - exporter
  - monitoring
  - finops
maintainers:
  - name: zgpcy
    url: https://github.com/zgpcy
home: https://github.com/zgpcy/azure-cost-exporter
sources:
  - https://github.com/zgpcy/azure-cost-exporter
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/prometheus/icon/color/prometheus-icon-color.svg
