{{- if and (not .Values.managedIdentity.enabled) (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-cost-exporter.fullname" . }}
  labels:
    {{- include "azure-cost-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.azure.clientId | b64enc | quote }}
  client-secret: {{ .Values.azure.clientSecret | b64enc | quote }}
  tenant-id: {{ .Values.azure.tenantId | b64enc | quote }}
{{- end }}
