{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-cost-exporter.serviceAccountName" . }}
  labels:
    {{- include "azure-cost-exporter.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.annotations (and .Values.managedIdentity.enabled (eq .Values.managedIdentity.type "workload-identity")) }}
  annotations:
    {{- if and .Values.managedIdentity.enabled (eq .Values.managedIdentity.type "workload-identity") }}
    azure.workload.identity/client-id: {{ .Values.managedIdentity.clientId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
